# Generated by Django 6.0 on 2025-12-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='coding_activity_order',
            field=models.IntegerField(default=50, help_text='Order position for coding activity section'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='github_username',
            field=models.CharField(blank=True, default='', help_text='Your GitHub username', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='leetcode_username',
            field=models.CharField(blank=True, default='', help_text='Your LeetCode username', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_coding_activity',
            field=models.BooleanField(default=False, help_text='Show GitHub/LeetCode contribution graphs'),
        ),
    ]
