# Generated by Django 6.0 on 2025-12-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_sitesettings_coding_activity_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_url',
            field=models.URLField(blank=True, default='', help_text='External icon URL (e.g., from DevIcon)'),
        ),
    ]
