# Generated by Django 6.0 on 2025-12-31 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_add_skill_icon_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, help_text='Hashed visitor identifier', max_length=64)),
                ('path', models.CharField(default='/', max_length=500)),
                ('section', models.CharField(blank=True, default='', help_text='Which section was viewed', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('device_type', models.CharField(blank=True, default='', help_text='desktop, mobile, tablet', max_length=20)),
                ('browser', models.CharField(blank=True, default='', max_length=100)),
                ('os', models.CharField(blank=True, default='', max_length=100)),
                ('referer', models.URLField(blank=True, default='', help_text='Where the visitor came from')),
                ('referer_domain', models.CharField(blank=True, default='', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(help_text='The portfolio owner being viewed', on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='app_pagevie_user_id_8a3fa0_idx'), models.Index(fields=['user', 'visitor_id'], name='app_pagevie_user_id_fb43a6_idx')],
            },
        ),
    ]
